apiVersion: v1
kind: Pod
metadata:
  name: ping
spec:
  containers:
  - name: ping
    image: localhost:5000/ping:latest
    command: ["./ping"]
    env:
    - name: HOSTNAME
      valueFrom:
        configMapKeyRef:
          name: tikal
          key: hostname
    - name: PORT
      valueFrom:
        configMapKeyRef:
          name: tikal
          key: port
