apiVersion: v1
kind: Pod
metadata:
  name: pong
  labels:
    app: pong
spec:
  containers:
  - name: pong
    image: localhost:5000/pong:latest
    command: ["./pong"]
    ports:
    - name: web
      containerPort: 9001
      protocol: TCP
    env:
    - name: PORT
      value: "9001"
